# Copyright 2026 Roblox Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: portscanner-scanner
  labels:
    app.kubernetes.io/name: portscanner
    app.kubernetes.io/component: scanner
automountServiceAccountToken: false
