version = 1
SPDX-PackageName = "portscanner"
SPDX-PackageDownloadLocation = "https://github.com/Roblox/portscanner"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Roblox"
SPDX-License-Identifier = "MIT"
