{{/*
Copyright 2026 Roblox Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
{{- $root := . -}}
{{- if $root.Values.scanner.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "portscanner.scannerServiceAccountName" $root }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "portscanner.labels" $root | nindent 4 }}
    app.kubernetes.io/component: scanner
  {{- with $root.Values.scanner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $root.Values.scanner.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- if $root.Values.scanner.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "portscanner.fullname" $root }}-scanner
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "portscanner.labels" $root | nindent 4 }}
    app.kubernetes.io/component: scanner
rules:
  {{- toYaml $root.Values.scanner.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "portscanner.fullname" $root }}-scanner
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "portscanner.labels" $root | nindent 4 }}
    app.kubernetes.io/component: scanner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "portscanner.fullname" $root }}-scanner
subjects:
  - kind: ServiceAccount
    name: {{ include "portscanner.scannerServiceAccountName" $root }}
    namespace: {{ $root.Release.Namespace }}
{{- end }}
