// Copyright 2026 Roblox Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *JobReference) DeepCopyInto(out *JobReference) {
	*out = *in
}

func (in *JobReference) DeepCopy() *JobReference {
	if in == nil {
		return nil
	}
	out := new(JobReference)
	in.DeepCopyInto(out)
	return out
}

func (in *PortRange) DeepCopyInto(out *PortRange) {
	*out = *in
}

func (in *PortRange) DeepCopy() *PortRange {
	if in == nil {
		return nil
	}
	out := new(PortRange)
	in.DeepCopyInto(out)
	return out
}

func (in *Scanner) DeepCopyInto(out *Scanner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Scanner) DeepCopy() *Scanner {
	if in == nil {
		return nil
	}
	out := new(Scanner)
	in.DeepCopyInto(out)
	return out
}

func (in *Scanner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ScannerList) DeepCopyInto(out *ScannerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Scanner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ScannerList) DeepCopy() *ScannerList {
	if in == nil {
		return nil
	}
	out := new(ScannerList)
	in.DeepCopyInto(out)
	return out
}

func (in *ScannerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ScannerSpec) DeepCopyInto(out *ScannerSpec) {
	*out = *in
	out.Target = in.Target
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.Ranges != nil {
		in, out := &in.Ranges, &out.Ranges
		*out = make([]PortRange, len(*in))
		copy(*out, *in)
	}
	in.Deadline.DeepCopyInto(&out.Deadline)
	in.NotAfter.DeepCopyInto(&out.NotAfter)
	in.SourceTimestamps.DeepCopyInto(&out.SourceTimestamps)
}

func (in *ScannerSpec) DeepCopy() *ScannerSpec {
	if in == nil {
		return nil
	}
	out := new(ScannerSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ScannerStatus) DeepCopyInto(out *ScannerStatus) {
	*out = *in
	if in.ActiveJobRef != nil {
		in, out := &in.ActiveJobRef, &out.ActiveJobRef
		*out = new(JobReference)
		**out = **in
	}
	if in.QueuedAt != nil {
		in, out := &in.QueuedAt, &out.QueuedAt
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ScannerStatus) DeepCopy() *ScannerStatus {
	if in == nil {
		return nil
	}
	out := new(ScannerStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ScannerTarget) DeepCopyInto(out *ScannerTarget) {
	*out = *in
}

func (in *ScannerTarget) DeepCopy() *ScannerTarget {
	if in == nil {
		return nil
	}
	out := new(ScannerTarget)
	in.DeepCopyInto(out)
	return out
}

func (in *SourceTimestamps) DeepCopyInto(out *SourceTimestamps) {
	*out = *in
	in.EventAt.DeepCopyInto(&out.EventAt)
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

func (in *SourceTimestamps) DeepCopy() *SourceTimestamps {
	if in == nil {
		return nil
	}
	out := new(SourceTimestamps)
	in.DeepCopyInto(out)
	return out
}
