# Copyright 2026 Roblox Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: portscanner-operator-leader-election
  labels:
    app.kubernetes.io/name: portscanner
    app.kubernetes.io/component: operator
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
