# Copyright 2026 Roblox Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portscanner-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - scanning.portscanner.io
  resources:
  - scanners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scanning.portscanner.io
  resources:
  - scanners/finalizers
  verbs:
  - update
- apiGroups:
  - scanning.portscanner.io
  resources:
  - scanners/status
  verbs:
  - get
  - patch
  - update
