# Copyright 2026 Roblox Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portscanner-operator
  labels:
    app.kubernetes.io/name: portscanner
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: portscanner-operator
subjects:
  - kind: ServiceAccount
    name: portscanner-operator
    namespace: portscanner-system
