# Copyright 2026 Roblox Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: portscanner-operator
  labels:
    app.kubernetes.io/name: portscanner
    app.kubernetes.io/component: operator
