#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Portscanner contributors
# SPDX-License-Identifier: MIT
"""Generate hashed Lambda runtime requirements from the workspace uv lock."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Final

ROOT: Final = Path(__file__).resolve().parents[1]
COMPONENTS: Final = {
    "portscanner-inventory": Path("inventory/requirements-runtime.txt"),
    "portscanner-generator": Path("generator/requirements-runtime.txt"),
    "portscanner-parser": Path("parser/requirements-runtime.txt"),
    "portscanner-processor": Path("processor/requirements-runtime.txt"),
    "portscanner-migrator": Path("db/migrator/requirements-runtime.txt"),
    "portscanner-scanner": Path("scanner/nmap/requirements-runtime.txt"),
}
BUILD_REQUIREMENTS: Final = Path("requirements-build.txt")
SPDX_PREFIX: Final = "# SPDX-"
HEADER: Final = (
    "# Generated by tools/export_runtime_requirements.py; do not edit.\n"
    f"{SPDX_PREFIX}FileCopyrightText: 2026 Portscanner contributors\n"
    f"{SPDX_PREFIX}License-Identifier: MIT\n"
    "\n"
)


def export_requirements(uv: str, package: str) -> str:
    """Return one package's frozen third-party dependency export."""

    command = (
        uv,
        "export",
        "--frozen",
        "--package",
        package,
        "--no-dev",
        "--no-emit-project",
        "--no-emit-workspace",
        "--no-header",
        "--no-annotate",
        "--format",
        "requirements.txt",
    )
    result = subprocess.run(  # noqa: S603 - uv is resolved to an absolute executable path.
        command,
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip()
        raise RuntimeError(f"uv export failed for {package}: {detail}")
    return HEADER + result.stdout.lstrip()


def export_build_requirements(uv: str) -> str:
    """Return frozen build-backend dependencies shared by component wheels."""

    result = subprocess.run(  # noqa: S603 - uv is resolved to an absolute executable path.
        (
            uv,
            "export",
            "--frozen",
            "--only-group",
            "build",
            "--no-header",
            "--no-annotate",
            "--format",
            "requirements.txt",
        ),
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip()
        raise RuntimeError(f"uv export failed for build requirements: {detail}")
    return HEADER + result.stdout.lstrip()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when an export differs",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    uv_name = os.environ.get("UV", "uv")
    uv = shutil.which(uv_name)
    if uv is None:
        sys.stderr.write(f"error: required uv executable not found: {uv_name}\n")
        return 2

    stale: list[Path] = []
    try:
        expected_build = export_build_requirements(uv)
        build_path = ROOT / BUILD_REQUIREMENTS
        if args.check:
            if not build_path.is_file() or build_path.read_text(encoding="utf-8") != expected_build:
                stale.append(BUILD_REQUIREMENTS)
        else:
            build_path.write_text(expected_build, encoding="utf-8")
        for package, relative_path in COMPONENTS.items():
            expected = export_requirements(uv, package)
            path = ROOT / relative_path
            if args.check:
                if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                    stale.append(relative_path)
            else:
                path.write_text(expected, encoding="utf-8")
    except (OSError, RuntimeError) as exc:
        sys.stderr.write(f"error: {exc}\n")
        return 2

    if stale:
        joined = ", ".join(path.as_posix() for path in stale)
        sys.stderr.write(
            "runtime requirements are stale: "
            f"{joined}; run `uv run python tools/export_runtime_requirements.py`\n"
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
